# Generated by Django 5.2.5 on 2026-01-20 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_complaint_subject_alter_complaint_product'),
        ('vendor', '0002_vendor_profile_picture_bankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.CharField(choices=[('Category', 'Category'), ('Size', 'Size'), ('Color', 'Color')], max_length=20)),
                ('attribute_value', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
