from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name='admin_dashboard'),
    path("customers/", views.manage_customers, name='manage_customers'),
    path("customers/<int:pk>/", views.detail_customer, name='detail_customer'),
    path("customers/add/", views.add_customer, name='add_customer'),
    path("customers/edit/<int:pk>/", views.edit_customer, name='edit_customer'),
    path("customers/delete/<int:pk>/", views.delete_customer, name='delete_customer'),
    path("vendors/", views.manage_vendors, name='manage_vendors'),
    path("vendors/<int:pk>/", views.detail_vendor, name='detail_vendor'),
    path("vendors/add/", views.add_vendor, name='add_vendor'),
    path("vendors/edit/<int:pk>/", views.edit_vendor, name='edit_vendor'),
    path("vendors/delete/<int:pk>/", views.delete_vendor, name='delete_vendor'),
    path("categories/", views.manage_categories, name='manage_categories'),
    path("categories/<int:pk>/", views.detail_category, name='detail_category'),
    path("categories/add/", views.add_category, name='add_category'),
    path("categories/edit/<int:pk>/", views.edit_category, name='edit_category'),
    path("categories/delete/<int:pk>/", views.delete_category, name='delete_category'),
    path("products/", views.manage_products, name='manage_products'),
    path("products/<int:pk>/", views.detail_product, name='detail_product'),
    path("products/add/", views.add_product, name='admin_add_product'),
    path("products/edit/<int:pk>/", views.edit_product, name='admin_edit_product'),
    path("products/delete/<int:pk>/", views.delete_product, name='admin_delete_product'),
    path("orders/", views.manage_orders, name='manage_orders'),
    path("orders/<int:pk>/", views.order_detail, name='admin_order_detail'),
    path('orders/edit/<int:pk>/', views.admin_edit_order, name='admin_edit_order'),
    path('shipments/', views.manage_shipments, name='manage_shipments'),
    path('shipments/<int:pk>/', views.detail_shipment, name='detail_shipment'),
    path('shipments/update/<int:pk>/', views.admin_update_shipment_status, name='admin_update_shipment_status'),
    path("payments/", views.manage_payments, name='manage_payments'),
    path("reviews/", views.view_reviews, name='view_reviews'),
    path('reviews/detail/<int:pk>/', views.detail_review, name='detail_review'),
    path('reviews/delete/<int:pk>/', views.delete_review, name='delete_review'),
    path("complaints/", views.view_complaints, name='view_complaints'),
    path('complaints/delete/<int:pk>/', views.delete_complaint, name='delete_complaint'),
    path("profile/", views.admin_profile, name='admin_profile'),
    path("change-password/", views.change_password, name='admin_change_password'),
    path('requests/', views.manage_requests, name='manage_requests'),
    path('requests/approve/<int:pk>/', views.approve_request, name='approve_request'),
    path('requests/reject/<int:pk>/', views.reject_request, name='reject_request'),
    path('sizes/', views.manage_sizes, name='manage_sizes'),
    path('sizes/delete/<int:pk>/', views.delete_size, name='delete_size'),
    path('colors/', views.manage_colors, name='manage_colors'),
    path('colors/delete/<int:pk>/', views.delete_color, name='delete_color'),
]
