# Generated by Django 5.2.5 on 2026-02-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlog',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='cart.order'),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='cart.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Netbanking'), ('wallet', 'Wallet'), ('emi', 'EMI')], max_length=50),
        ),
    ]
